#!/usr/bin/env python3
"""
Module that defines a coroutine to collect 10 random floats
using an async comprehension.
"""

import asyncio
from typing import List

async_generator = __import__('0-async_generator').async_generator


async def async_comprehension() -> List[float]:
    """
    Asynchronous coroutine that collects 10 random float numbers
    generated by async_generator using an async comprehension.

    Returns:
        List[float]: A list containing 10 random float values between 0 and 10.
    """
    result = [x async for x in async_generator()]
    return result
